import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type Row = { id:number; registration_id:string; email:string; total_amount:number; payment_mode:string; payment_reference:string; status:string; participant_count:number; created_at:string }
export default function Admin() {
  const [token,setToken]=useState(''); const [rows,setRows]=useState<Row[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  async function load(){ setLoading(true); setError(''); try { const r=await fetch('/api/admin/registrations',{headers:{authorization:`Bearer ${token}`}}); const j=await r.json() as {registrations?:Row[];error?:string}; if(!r.ok) throw new Error(j.error||'Could not load'); setRows(j.registrations||[]) } catch(e){setError(e instanceof Error?e.message:'Could not load')} finally{setLoading(false)} }
  async function status(id:number,value:string){ const r=await fetch(`/api/admin/registrations/${id}`,{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({status:value})}); if(r.ok) load() }
  return <main className="min-h-dvh bg-background px-gutter py-10"><div className="mx-auto max-w-content"><h1 className="text-4xl">NHYM 2026 Registration Admin</h1><p className="mt-2 text-muted-foreground">Enter the private admin token configured in Cloudflare.</p><div className="mt-6 flex max-w-xl gap-2"><Input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin token"/><Button onClick={load}>{loading?'Loading…':'Load registrations'}</Button></div>{error&&<p className="mt-3 text-destructive">{error}</p>}<div className="mt-8 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">ID</th><th>Email</th><th>Participants</th><th>Total</th><th>Payment reference</th><th>Status</th><th>Submitted</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="p-2 font-mono">{r.registration_id}</td><td>{r.email}</td><td>{r.participant_count}</td><td>₹{r.total_amount.toLocaleString('en-IN')}</td><td>{r.payment_mode} · {r.payment_reference}</td><td><select className="rounded border bg-background p-2" value={r.status} onChange={e=>status(r.id,e.target.value)}><option>PENDING</option><option>PAYMENT_VERIFIED</option><option>APPROVED</option><option>REJECTED</option></select></td><td>{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></div></main>
}
